#############################################################################
# Makefile for building: tfblog
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  tfblog.pro
# Template: subdirs
# Command: /usr/lib/qt/bin/qmake CONFIG+=debug -o Makefile tfblog.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-helpers \
		sub-models \
		sub-views \
		sub-controllers


sub-helpers-qmake_all:  FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile
	cd helpers/ && $(MAKE) -f Makefile qmake_all
sub-helpers: FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-helpers-make_first: FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-helpers-all: FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-helpers-clean: FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-helpers-distclean: FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-helpers-install_subtargets: FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-helpers-uninstall_subtargets: FORCE
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-models-qmake_all:  FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile
	cd models/ && $(MAKE) -f Makefile qmake_all
sub-models: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-models-make_first: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-models-all: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-models-clean: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-models-distclean: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-models-install_subtargets: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-models-uninstall_subtargets: FORCE
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-views-qmake_all:  FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile
	cd views/ && $(MAKE) -f Makefile qmake_all
sub-views: FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-views-make_first: FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-views-all: FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-views-clean: FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-views-distclean: FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-views-install_subtargets: FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-views-uninstall_subtargets: FORCE
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-controllers-qmake_all:  FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile
	cd controllers/ && $(MAKE) -f Makefile qmake_all
sub-controllers: FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-controllers-make_first: FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-controllers-all: FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-controllers-clean: FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-controllers-distclean: FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-controllers-install_subtargets: FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-controllers-uninstall_subtargets: FORCE
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: tfblog.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/shell-unix.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		tfblog.pro
	$(QMAKE) CONFIG+=debug -o Makefile tfblog.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/shell-unix.conf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
tfblog.pro:
qmake: FORCE
	@$(QMAKE) CONFIG+=debug -o Makefile tfblog.pro

qmake_all: sub-helpers-qmake_all sub-models-qmake_all sub-views-qmake_all sub-controllers-qmake_all FORCE

make_first: sub-helpers-make_first sub-models-make_first sub-views-make_first sub-controllers-make_first FORCE
all: sub-helpers-all sub-models-all sub-views-all sub-controllers-all FORCE
clean: sub-helpers-clean sub-models-clean sub-views-clean sub-controllers-clean FORCE
distclean: sub-helpers-distclean sub-models-distclean sub-views-distclean sub-controllers-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-helpers-install_subtargets sub-models-install_subtargets sub-views-install_subtargets sub-controllers-install_subtargets FORCE
uninstall_subtargets: sub-helpers-uninstall_subtargets sub-models-uninstall_subtargets sub-views-uninstall_subtargets sub-controllers-uninstall_subtargets FORCE

sub-helpers-check:
	@test -d helpers/ || mkdir -p helpers/
	cd helpers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/helpers/helpers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-models-check:
	@test -d models/ || mkdir -p models/
	cd models/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/models/models.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-views-check:
	@test -d views/ || mkdir -p views/
	cd views/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/views/views.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-controllers-check:
	@test -d controllers/ || mkdir -p controllers/
	cd controllers/ && ( test -e Makefile || $(QMAKE) /home/ck/src/tfblog/controllers/controllers.pro CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-helpers-check sub-models-check sub-views-check sub-controllers-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

